### Prueba de correo exitoso, con todos los datos completos
POST    http://localhost/api-carol/v1/endpoint-webservice/
Content-Type: "application/json"

{
    "name": "Invitado",
    "email": "invitado@gmail.com",
    "message": "Prueba" 
}

### Prueba de correo un dato faltante
POST    http://localhost/api-carol/v1/endpoint-webservice/
Content-Type: "application/json"

{
    "name": "Invitado",
    "email": "",
    "message": "Primera prueba" 
}

### Prueba de correo con email erróneo
POST    http://localhost/api-carol/v1/endpoint-webservice/
Content-Type: "application/json"

{
    "name": "Invitado",
    "email": "invitadogmail.com",
    "message": "Segunda prueba" 
}

### Prueba de correo con todos los datos faltantes(Tercera prueba)
POST    http://localhost/api-carol/v1/endpoint-webservice/
Content-Type: "application/json"

{
    "name": "",
    "email": "",
    "message": "" 
}